import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./components/footer";
import NavBar from "./components/navBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <section className="max-w-6xl mx-auto content-center">
          <NavBar />
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
