import type { Metadata } from "next";
import "./globals.css";
import NavTabs from "./components/NavBar";
import { Footer } from "./components/Footer";
import { Container } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavTabs />
        <Container maxWidth="lg">{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
